name: flutter_twitter_project
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  video_player: ^2.4.7
  awesome_icons: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  provider: ^6.0.3

flutter:
  uses-material-design: true

  assets:
  - images/
  - assets/

#  fonts:
#  - family: Schyler
#    fonts:
#    - asset: fonts/Schyler-Regular.ttf
#    - asset: fonts/Schyler-Italic.ttf
#      style: italic


